baseURL = 'http://guangliang.li/'
languageCode = 'en-us'
theme = "Hugo-JuiceBar"
title = "Robin Blog"
# 有效
[params]
author = "Robin"
description = "echnology, information security, daily life, system administration, system operations"
authorImage = "https://images.guangliang.li/45F8CC1E-6BB0-4FEF-8E37-49C116657149_1_105_c.jpeg"
paginate = 10
Title = "Robin"
content = "Recording my postgraduate life in Malaysia"
imageUrl = "https://images.guangliang.li/45F8CC1E-6BB0-4FEF-8E37-49C116657149_1_105_c.jpeg"

# 添加新的社交图标
# 更多社交图标可以在JuiceBar\layouts\partials\svg.html中找到
#[[params.social]]
#name = "Github"
#url = "https://github.com/null"
#[[params.social]]
#name = "telegram"
#url = "https://t.me/null"
#[[params.social]]
#name = "twitter"
#url = "https://twitter.com/null"
[[params.social]]
name = "email"
url = "mailto:im@guangliang.li"
#[[params.social]]
#name = "instagram"
#url = "your_url"
#[[params.social]]
#name = "mastodon"
#url = "your_url"
#[[params.social]]
#name = "reddit"
#url = "your_url"
#[[params.social]]
#name = "stackoverflow"
#url = "your_url"

[taxonomies]
category = "categories"
tag = "tags"

# 添加新的导航链接
[[menu.main]]
name = "About"
url = "/about/"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# 如果使用giscus评论系统
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

#用于输出文档的设置（必须的）
[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
post = "/:filename"